import Navbar from '@/components/navbar'
import { AuthContextProvider } from '@/context/auth-context'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Movieees',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <body className={inter.className}>
          <div className="flex min-h-screen max-w-[1700px] m-auto flex-col py-6 px-4 lg:p-10">
            <Navbar />
            {children}
          </div>
        </body>
      </AuthContextProvider>
    </html>
  )
}
